### ISSUE TITLE
Bora ressuscitar isso aqui?

### ISSUE THREAD

**Issue by ryukinix** [NeowayLabs/neowaylabs.github.io#1]
@cadicallegari @lborguetti @boechat107

**Comment by ryukinix** [comment]
base escolhida pra fork: https://mmistakes.github.io/so-simple-theme/

**Comment by lborguetti** [comment]
Boraaa! =]

**Comment by lborguetti** [comment]
@thiagocaiubi @ppizarro

**Comment by ryukinix** [comment]
@katcipis Sugestões?

**Comment by ryukinix** [comment]
Exemplo de conceito q trabalhei nesse fim de semana: datascience-ufc.github.io
