### ISSUE TITLE
[CSS] Refactor div.highlighter-rouge

### ISSUE THREAD

**Issue by ryukinix** [NeowayLabs/neowaylabs.github.io#3]
The currently style is not so nice to read:

![image](https://user-images.githubusercontent.com/7642878/53931283-4a17c800-4073-11e9-93d9-2354bea4eede.png)

I think the contrast can be better. The CSS responsabile for that is the color and background keys at these rules:

https://github.com/NeowayLabs/neowaylabs.github.io/blob/7f5140c5ec65842de7723224bccdeaa1b073490f/_sass/so-simple/_syntax-highlighting.scss#L7-L26

https://github.com/NeowayLabs/neowaylabs.github.io/blob/7f5140c5ec65842de7723224bccdeaa1b073490f/_sass/so-simple/_variables.scss#L100-L106

**Comment by ryukinix** [comment]
Proposed change: neowaylabs.lerax.me

**Comment by katcipis** [comment]
I can't see the difference between this and the original one (comparing the lerax with neowaylabs.github.io)

**Comment by ryukinix** [comment]
Sorry, I forget to update I think

**Comment by ryukinix** [comment]
Look here: https://neowaylabs.lerax.me/programming/unix-shell-for-data-scientists/
